version: "3.8"

services:
  auth:
    build:
      context: ./auth
    deploy:
      replicas: 2
    environment:
      DATABASE_PASSWORD: creatorsyard
      DATABASE_USERNAME: creatorsyard
      DATABASE_NAME: creatorsyard
      DATABASE_HOST: auth-db
      SECRET_KEY: 94d15ae4e75814170203eec4e8e735e1
      PORT: 8080
      CLIENT_URL: http://client:3000
    depends_on:
      - auth-db

  client:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - videos
      - auth
      - auth-db
      - analysis
      - analysis-db

  videos:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./video
    deploy:
      replicas: 3
    volumes:
      - creatorsyard_video_volume:/storage
    environment:
      PORT: 8081
      AI_URL: http://host.docker.internal:8083
      CLIENT_URL: http://client:3000
      SECRET_KEY: 94d15ae4e75814170203eec4e8e735e1
      STORAGE_PATH: /storage
  analysis:
    deploy:
      replicas: 3
    build:
      context: ./scrapers
    environment:
      CLIENT_URL: http://client:3000
      DB_CONNECT: mongodb://analysis-db:27017/analysis
      SECRET_KEY: 94d15ae4e75814170203eec4e8e735e1
      PORT: 8082

    depends_on:
      - analysis-db
  analysis-db:
    image: mongo:latest
    volumes:
      - creatorsyard_analysis_db:/data/db
    environment:
      POSTGRES_PASSWORD: creatorsyard
      POSTGRES_USER: creatorsyard
      POSTGRES_DB: creatorsyard
  auth-db:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_PASSWORD: creatorsyard
      POSTGRES_USER: creatorsyard
      POSTGRES_DB: creatorsyard
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - creatorsyard_auth_db:/var/lib/postgresql/data
volumes:
  creatorsyard_auth_db:
  creatorsyard_analysis_db:
  creatorsyard_video_volume:
