version: "3.8"
services:
  server:
    build: .
    environment:
      DATABASE_PASSWORD: creatorsyard
      DATABASE_USERNAME: creatorsyard
      DATABASE_NAME: creatorsyard
      DATABASE_HOST: db
      SECRET_KEY: 94d15ae4e75814170203eec4e8e735e1
      STORAGE_PATH: /storage
      PORT: 8080
      CLIENT_URL: http://localhost:3000
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_PASSWORD: creatorsyard
      POSTGRES_USER: creatorsyard
      POSTGRES_DB: creatorsyard
